/**
 * Core Investment Tracker API
 * Investment tracker is a platform that allows you to track aspects that affect your investments
 *
 * OpenAPI spec version: v1
 * Contact: 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Investment } from './investment';
import { InvestmentTransaction } from './investmentTransaction';


export interface InvestmentTransactionInvestment { 
    transactionID?: number;
    transaction?: InvestmentTransaction;
    /**
     * 
     */
    investmentID?: number;
    /**
     * 
     */
    investment?: Investment;
}
