/**
 * Core Investment Tracker API
 * Investment tracker is a platform that allows you to track aspects that affect your investments
 *
 * OpenAPI spec version: v1
 * Contact: 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Represents a transaction on an investment
 */
export interface InvestmentTransaction {
    /**
     * The investment this transaction is for
     */
    investmentID?: number;
    /**
     * The number of units bought
     */
    numUnits?: number;
    /**
     * The price per unit
     */
    pricePerUnit?: number;
    /**
     * ISO code that represents the currency
     */
    currency?: string;
    /**
     * Eg Buy, Sell
     */
    transactionType?: string;
    /**
     * Time that the transaction was made
     */
    transactionDate?: Date;
    readonly investmentIds?: Array<number>;
    /**
     * The identifier of the entity
     */
    id?: number;
    /**
     * The name of the entity
     */
    name?: string;
    /**
     * The description of the entity
     */
    description?: string;
    /**
     * When the entity was created
     */
    createdTime?: Date;
    /**
     * When the entity was last modified
     */
    lastModifiedTime?: Date;
    /**
     * Generic points for this entity
     */
    points?: number;
    /**
     * Generic true/false marker for entity
     */
    isFlagged?: boolean;

    commision: string;
}
