language: node_js
node_js:
   - node # will use latest node
os: linux
dist: trusty
sudo: required
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce
before_script: # commands to run before the build step
   - npm install -g --silent @angular/cli
script:
  - chmod +x ./deploy-envs.sh
  - chmod +x ./angular-build-prod.sh
  - chmod +x ./scripts/build.sh
  - chmod +x ./scripts/deploy.sh
  - cd scripts && ./build.sh
  - if [ "$TRAVIS_BRANCH" == "master" ]; then ./deploy.sh; fi
