language: node_js
node_js:
   - node # will use latest node
os: linux
dist: trusty
sudo: required
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce
before_script: # commands to run before the build step
   - npm install -g @angular/cli
after_success:
   - docker --version
   - pip install --user awscli
   - export PATH=$PATH:$HOME/.local/bin # put aws in the path
   - export AWS_ECS_REPO_DOMAIN=$AWS_ACCOUNT_NUMBER.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com   
   - eval $(aws ecr get-login --region $AWS_DEFAULT_REGION) #needs AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY envvars
   - docker build -t$IMAGE_NAME .
   - docker tag $IMAGE_NAME:latest $AWS_ECS_REPO_DOMAIN/$IMAGE_NAME:latest
   - docker push $AWS_ECS_REPO_DOMAIN/$IMAGE_NAME:latest
#script:
#  - ng build --env=prod
#  - chmod +x ./deploy-envs.sh
#  - chmod +x ./scripts/build.sh
#  - chmod +x ./scripts/deploy.sh
#  - cd scripts && ./build.sh
#  - if [ "$TRAVIS_BRANCH" == "master" ]; then ./deploy.sh; fi
