language: node_js
os: linux
dist: trusty
sudo: required
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce
before_script:
   - npm install
script:
  - chmod +x ./deploy-envs.sh
  - chmod +x ./angular-build-prod.sh
  - chmod +x ./scripts/build.sh
  - chmod +x ./scripts/deploy.sh
  - cd scripts && ./build.sh
  - if [ "$TRAVIS_BRANCH" == "master" ]; then ./deploy.sh; fi
