language: node_js
node_js:
   - node # will use latest node
os: linux
dist: trusty
sudo: required
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce
before_script: # commands to run before the build step
   - npm install -g @angular/cli
after_success:
   - docker --version
   - pip install --user awscli
   - export PATH=$PATH:$HOME/.local/bin # put aws in the path
   - sudo apt-get install jq -y #install jq for json parsing
   - sudo apt-get install gettext -y 
script:
  - ng build --env=prod
  - chmod +x ./deploy-envs.sh
  - chmod +x ./scripts/build.sh
  - chmod +x ./scripts/deploy.sh
  - cd scripts && ./build.sh
  - if [ "$TRAVIS_BRANCH" == "master" ]; then ./deploy.sh; fi
