language: node_js
node_js:
   - node # will use latest node
os: linux
dist: trusty
sudo: required
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce
before_script: # commands to run before the build step
   - npm install -g @angular/cli
   - sudo apt-get -y update
   - sudo -H pip install --upgrade pip
   - sudo pip install pyOpenSSL ndg-httpsclient pyasn1
   - sudo apt-get install jq -y #install jq for json parsing
   - sudo apt-get install gettext -y 
   - pip install --user awscli # install aws cli w/o sudo
script:
  - ng build --env=prod
  - chmod +x ./deploy-envs.sh
  - chmod +x ./scripts/build.sh
  - chmod +x ./scripts/deploy.sh
  - cd scripts && ./build.sh
  - if [ "$TRAVIS_BRANCH" == "master" ]; then ./deploy.sh; fi
